name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: goodsciproj_env
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Conda Info
        run: |
          conda info
          conda list

      - name: Activate Conda Environment
        run: |
          conda init
          source /home/runner/.bashrc
          conda activate /usr/share/miniconda/envs/goodsciproj_env
          conda info --envs

      - name: Build Pybind11 module for C++ code
        run: |
          cmake -S ./ -B ./build
          cd build && make
      - name: Test with pytest
        run: pytest ./tests

      - name: Install Doxygen
        run: /usr/share/miniconda/envs/goodsciproj_env/bin/doxygen --version
        shell: bash
      - name: Generate Doxygen Documentation
        run: |
          cd docs &&
          mkdir build &&
          mkdir build/doxygen &&
          /usr/share/miniconda/envs/goodsciproj_env/bin/doxygen doxygen/doxygen.dox
        shell: bash

      - name: Build docs
        run: |
          cd docs && make html
      - name: Archive build artifacts (i.e. documentation)
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/

  publish:
    needs: build
    # Only publish documentation when merging into `origin/main`.`
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'yoctoyotta1024'"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts (i.e. documentation)
        uses: actions/download-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Publish docs on github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
